//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

/// <summary>
/// Represents a todo item.
/// </summary>
namespace TodoApi.Models
{
    /// <summary>
    /// Represents a todo item.
    /// </summary>
    public class TodoItem
    {
        /// <summary>
        /// Gets or sets the ID of the todo item.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the title of the todo item.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets the description of the todo item.
        /// </summary>
        public string Description { get; set; }
    }
}